### ISSUE TITLE
calendar: optimizing layout

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#206]
for a better understanding the YEAR-overview should be more visible as well as the forward/backward arrow on the sides in the mobile version (carousel).

**Comment by jocarstensen** [comment]
The names of the months are not placed correctly on small screens. Can this be fixed?

**Comment by dzhwmeisner** [comment]
header and buttons restyled. label placement fixed. Please test at

http://vmzofar-pres.his.de:8080/devhtml5/page15.html

**Comment by jocarstensen** [comment]
- Can only test using developer tools in firefox since server is not accessible from outside. Is there an easy way to access the test page via smartphone?

- Years look good!

- Months not correctly placed on small screens (e.g. iphone 6/7/8 (plus)) in landscape mode.

- Threshold for months (horizontal vs. vertical alignment): Font size becomes quite small before turning vertical. Can you set the threshold earlier?

**Comment by se-lang** [comment]
Nothing to add but 2 points:

- There is one animation when using the years above the calendar for navigation, that is a little bit strange. After clicking on a new year the current year switches to the smallest fontsize and the lightest grey until the rotation of the calendar is finished. After rotation is finished it switches to the new correct size and color.

- Only a minor point but can you "optimize" the white space above and below? IMO we lose quite some space here especially on small screens in landscape mode.

**Comment by andreaschu** [comment]
I close this, because the carousel is not used within the new calendar.
