### ISSUE TITLE
calendar: objektbasierte Variablen

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#291]
Speicherung von Objekten in JSON-Struktur

**Comment by andreaschu** [comment]
please check for functionality: http://vmtest.dzhw.local:8080/EpisodesPoC

**Comment by andreaschu** [comment]
strange behavior when using the input field: there is a month set default (e.g. January or March), that is before the month you are in. So if you are not recognising it, it may be not saved because the end-date is before the start-date.

![grafik](https://user-images.githubusercontent.com/30111489/73375588-4b219b80-42bc-11ea-9930-b1922ec4f179.png)

**Comment by andreaschu** [comment]
As zofar user I want to identify a type of the episode to lead the respondent only to relevant modules. Is this possible with this solution?

**Comment by andreaschu** [comment]
The prototype is fininished and the requirement will emerge in new issues, so I close this issue.
