### ISSUE TITLE
Carousell - counter for item number

### ISSUE THREAD

**Issue by kastirke** [dzhw/zofar#37]
Shall we add an indicator for the item number (see clickable counter in the lower picture)?

![grafik](https://user-images.githubusercontent.com/30147532/31726477-63f67728-b427-11e7-9763-31be3b6d22e7.png)

![unbenannt](https://user-images.githubusercontent.com/30147532/31726810-35a45970-b428-11e7-8871-69837a543510.png)

**Comment by dzhwmeisner** [comment]
need to test

**Comment by Miktarbad** [comment]
looks good. 

[ A ]On SCMs a little more space top&bottom would be good - otherwise the counter cuts into itemtexts.

[ B ] On Double SCMs itemtexts & counter are not visible. (Mobile Samsung S7 & Desktop )
![scm-counter1](https://user-images.githubusercontent.com/29864065/37325714-54ea3532-268f-11e8-97c6-3628229e0243.jpg)

**Comment by Miktarbad** [comment]
Sprint 8: developed to be tested

Sprint 9: testing, bug-fixing, finishing.

**Comment by kastirke** [comment]
Happy about the draft! :)

[D] Counter (and carousell navigators) too discreet, should be more showy (shades, colors ???) -> Responders` attention should focus on carousell navigation instead of survey navigation (Zurück" and "Weiter).
[E] Can you shift the counter from "under the item" to "between the carousell navigators"?

now checked with iPhone SE, iOS 11.2.6, Safari:
[C] SC Materix with values: values are visible

**Comment by Miktarbad** [comment]
is the counter currently disabled?

**Comment by dzhwmeisner** [comment]
need to test

**Comment by Miktarbad** [comment]
looks fixed - no further problems raised - closed
