### ISSUE TITLE
export automation

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#402]
For a (partially) automated export supply.

**Comment by andreaschu** [comment]
sometimes the page_list lead to a Number n+1 like in:
`egen_str='egen dauer=rowtotal(p0-p{0})'.format(len(page_list))`

The same indicator leads to n if it is integrated in loops (like in the loop for `label_maxpage_str`). I don't get why.

**Comment by christian-fr** [comment]
Oh... okay, so this could be because of the following behaviour (example):

```
liste = ['a', 'b', 'c']
```

The length of the list is 3:
```
len(liste)
> 3
```
But because the indices start at 0, they only go as far as 2:

```
liste[0]
> 'a'

liste[1]
> 'b'

liste[2]
> 'c'

liste[3]
> IndexError: list index out of range
``` 


So, with the above example, a for-loop 
```
for i in range(len(liste)):
    print(p{0}.format(i))
```

would iterates from i==0 to i==2, therefore putting out the following results:
```
> 'p0'
> 'p1'
> 'p2'
```

So the maximum "p"-Number would be 'p2', whereas `len(liste)` results to 3. So we would have to subtract 1 from the length to get the maximum index of the list: 
```
len(liste) -1
```
-----------------
Applied to your Python code above, this would mean:

```
egen_str='egen dauer=rowtotal(p0-p{0})'.format(len(page_list)-1)
```

**Comment by andreaschu** [comment]
> `egen_str='egen dauer=rowtotal(p0-p{0})'.format(len(page_list)-1)`

Thanks. I guessed that something like that would be the solution. I just didn't get the problem.

**Comment by christian-fr** [comment]
- improved the user interface (automatic search for `data.csv.zip`, `history.csv.zip`, `questionnaire.xml`).
- added a logger (creates a `log___main__.log` file with logging information.
- added a `--debug` parameter switch for verbose logging - can be run via the file `create_new_project_folder_structure_debug.bat`

**Comment by andreaschu** [comment]
Works great!
I close this issue for now. 
Let's open smaller issues for refinement and enhancement.
