### ISSUE TITLE
Calendar: Tests for verifier

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#520]
As a Zofar-User I need tests for Episode Data within the verifier.
As a researcher I want to assure data integrity.

----
- Test the usage of fragment variables: 
     - if combination in frag and defrag-functions are consistent

**Comment by andreaschu** [comment]
At first we need an overview what is needed to use the verifier for questionnaires with calendar and episode data.

**Comment by andreaschu** [comment]
Add test for consistency of episode variables: Are variables used within episode module (defined as used in triggers frag/defrag) also used in the project beyond episode data?

**Comment by dzhwmeisner** [comment]
Dummy FunctionProvider for Condition-Checks hve to be extended by episode-specific functions according to the 
real FunctionProvider

Add Episode-specific TestSuite to verifier containing initial 4 Tests 
    - no usage of Episode-Variables outside of Module-Pages (Pages containing common Episodes Trigger (frac,defrac))
    - no usage of Fragment-Variables outside of Module-Pages (Pages containing common Episodes Trigger (frac,defrac))
    - All Fragment-Variables are defined
    - No usage of Non-Episode-Variables at Module-Pages

Modify PageIntegrity TestSuite to consider pages with redirects as Entry-Point instead of transitions

**Comment by dzhwmeisner** [comment]
Implemented and commited : 

Add Episode-specific TestSuite to verifier containing initial 4 Tests
- no usage of Episode-Variables outside of Module-Pages (Pages containing common Episodes Trigger (frac,defrac))
- no usage of Fragment-Variables outside of Module-Pages (Pages containing common Episodes Trigger (frac,defrac))
- All Fragment-Variables are defined
- No usage of Non-Episode-Variables at Module-Pages

Modify PageIntegrity TestSuite to consider pages with redirects as Entry-Point instead of transitions

Still TODO: Extension of dummy FunctionProvider

**Comment by andreaschu** [comment]
I close this issue. For the open tasks, there is a new issue (#543).
