### ISSUE TITLE
Code Convention section

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#98]
As Zofar User we need a Code Convention to declare Structures we need to design Surveys and to identify logical Units for MDM-Export

**Comment by UteH** [comment]
### sections
- **we need to talk about how to deal with sections for the mdm question export** (format for instructions, introductions, topics)
- **now**
  - SISO or a "manual" what to do
  - we need to discuss this, because please remember that we said: please do not put effort in mannually beautifying sections
    - so is this an example of the "costs" that come with automization if we decide to not do manual beautifying?
  - we need to write this down
- **future**
  - Can we avoid this in the future somehow (code conventions?) 
  - we need to write this down

**Comment by andreaschu** [comment]
@UteH lists the errors of the example project Wissenschaftlerbefragung 
@dzhwmeisner and @Miktarbad will define code conventions if possible

**Comment by UteH** [comment]
we will tackle code conventions in general in #103
